name: Release build

on:
 schedule:
    - cron: '*/5 * * * *'
 workflow_dispatch:
    inputs:
      name: 
        description: "Want to inject something to build?"
        default: "no"

    
jobs:
 tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
       fetch-depth: 0
       
    - name: Hello Step
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1.67.0 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
