name: Release build

on:
 schedule:
    - cron: '*/5 * * * *'
 workflow_dispatch:
    inputs:
      name: 
        description: "Want to inject something to build?"
        default: "no"

    
jobs:
 tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
    - uses: actions/checkout@v4
    - name: Hello Step
      run: echo "Hello ${{ github.event.inputs.name }}"
